// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// KL_min_index
int KL_min_index(const std::vector<double>& w, Rcpp::List Sigma, Rcpp::List mu, char model_type);
RcppExport SEXP _bagel_KL_min_index(SEXP wSEXP, SEXP SigmaSEXP, SEXP muSEXP, SEXP model_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type w(wSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mu(muSEXP);
    Rcpp::traits::input_parameter< char >::type model_type(model_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(KL_min_index(w, Sigma, mu, model_type));
    return rcpp_result_gen;
END_RCPP
}
// find_min_err_index
List find_min_err_index(const std::vector<double>& w, Rcpp::List mu, Rcpp::List Sigma);
RcppExport SEXP _bagel_find_min_err_index(SEXP wSEXP, SEXP muSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type w(wSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(find_min_err_index(w, mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bagel_KL_min_index", (DL_FUNC) &_bagel_KL_min_index, 4},
    {"_bagel_find_min_err_index", (DL_FUNC) &_bagel_find_min_err_index, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bagel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
