# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KL_min_index <- function(w, Sigma, mu, model_type) {
    .Call('_bagel_KL_min_index', PACKAGE = 'bagel', w, Sigma, mu, model_type)
}

find_min_err_index <- function(w, mu, Sigma) {
    .Call('_bagel_find_min_err_index', PACKAGE = 'bagel', w, mu, Sigma)
}

